name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [backend, client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd CodeDesk/${{ matrix.dir }}
          npm ci
      - name: Run lint
        run: |
          cd CodeDesk/${{ matrix.dir }}
          npx eslint . || echo "Lint failed, continuing..."
      - name: Build
        run: |
          cd CodeDesk/${{ matrix.dir }}
          npm run build || echo "No build script"
      - name: Run tests
        run: |
          cd CodeDesk/${{ matrix.dir }}
          npm test